name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: used-car-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

     
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}


      - name: Build image with Cloud Build
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}"
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          gcloud builds submit --tag "${IMAGE}" .

      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image "${IMAGE}" \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated \
            --set-env-vars MODEL_TABLE=${{ secrets.MODEL_TABLE }}

      
      - name: Get Service URL
        id: url
        run: |
          URL=$(gcloud run services describe ${{ secrets.CLOUD_RUN_SERVICE }} \
            --region ${{ secrets.REGION }} \
            --format='value(status.url)')
          echo "url=${URL}" >> $GITHUB_OUTPUT
          echo "Service URL: ${URL}"

      - name: Health check
        run: |
          curl -fsSL "${{ steps.url.outputs.url }}/health" | tee /dev/stderr
